[package]
name = "rss-aggregator-lite"
version = "0.1.0"
edition = "2024"

[lib]
name = "core"
path = "src/lib.rs"

[[bin]]
name = "bin"
path = "src/main.rs"


[dependencies]
tokio = { version = "1.44.1", features = ["full"] }
rss = "2.0.12"
