

[settings]
is_offline = false
download_behavior = "all"

[feed]
feeds = ["https://lobste.rs/rss","https://www.volksverpetzer.de/rss","https://doingfedtime.com/rss", "https://2.5admins.com/feed/podcast"]
