//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "item")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub link: String,
    pub author: String,
    pub description: String,
    pub pub_date: String,
    pub content: String,
    pub enclosure: i32,
    pub categories: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::category::Entity",
        from = "Column::Categories",
        to = "super::category::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Category,
    #[sea_orm(
        belongs_to = "super::enclosure::Entity",
        from = "Column::Enclosure",
        to = "super::enclosure::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Enclosure,
}

impl Related<super::category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Category.def()
    }
}

impl Related<super::enclosure::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Enclosure.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
